webp.lo: /home/rainkid/workspace/webp/webp.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/rainkid/workspace/webp $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/rainkid/workspace/webp/webp.c -o webp.lo 
$(phplibdir)/webp.la: ./webp.la
	$(LIBTOOL) --mode=install cp ./webp.la $(phplibdir)

./webp.la: $(shared_objects_webp) $(WEBP_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_webp) $(WEBP_SHARED_LIBADD)

